name: 阿里云ACR自动化流水线

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # 每周日UTC时间00:00（北京时间周一8:00）

env:
  # 阿里云ACR配置（替换为您的实际信息）
  REGISTRY: registry.cn-hangzhou.aliyuncs.com  # 仓库地域地址
  NAMESPACE: ai-mnist                          # 命名空间名称
  REPOSITORY: mnist-api                        # 仓库名称
  IMAGE_TAG: latest

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 检出代码
    - name: 检出代码
      uses: actions/checkout@v3
      
    # 2. 设置Python环境（清华源加速）
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
        pip install -r requirements.txt torch torchvision onnx
        
    # 3. 训练模型
    - name: 训练模型
      run: |
        cd notebooks
        python train_model.py
        
    # 4. 构建Docker镜像
    - name: 构建镜像
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} .
        
    # 5. 登录阿里云ACR
    - name: 登录ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ALIYUN_ACR_USERNAME }}
        password: ${{ secrets.ALIYUN_ACR_PASSWORD }}
        
    # 6. 推送镜像到ACR
    - name: 推送镜像
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
        
    # 7. 服务器部署
    - name: 服务器部署
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 登录阿里云ACR
          docker login -u ${{ secrets.ALIYUN_ACR_USERNAME }} -p ${{ secrets.ALIYUN_ACR_PASSWORD }} ${{ env.REGISTRY }}
          
          # 拉取最新镜像
          docker pull ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          
          # 重启容器
          docker stop mnist-container || true
          docker rm mnist-container || true
          docker run -d \
            --name mnist-container \
            -p 5000:5000 \
            -p 8000:8000 \
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
