name: 阿里云ACR自动化流水线

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # 每周日UTC时间00:00（北京时间周一8:00）

env:
  # 替换为您的个人版ACR地址
  REGISTRY: crpi-awpzezftnb095rf0.cn-hangzhou.personal.cr.aliyuncs.com
  NAMESPACE: ai-mnist
  REPOSITORY: mnist-api
  IMAGE_TAG: latest

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 检出代码
    - name: 检出代码
      uses: actions/checkout@v3
      
    # 2. 设置Python环境（清华源加速）
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: 安装依赖
      run: |
        pip install --upgrade pip
        pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

        # 分步安装+超时设置
        pip install --timeout 600 -r requirements.txt
        pip install --timeout 600 torch==2.3.1 torchvision==0.18.1 onnx==1.16.0 -f https://download.pytorch.org/whl/cpu/torch_stable.html
        
    # 3. 训练模型
    - name: 训练模型
      run: |
        cd notebooks
        python train_model.py
        
    # 4. 构建Docker镜像
    - name: 构建镜像
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} .
        
    # 5. 登录阿里云ACR
    - name: 登录ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ALIYUN_ACR_USERNAME }}
        password: ${{ secrets.ALIYUN_ACR_PASSWORD }}
        
    # 6. 推送镜像到ACR
    - name: 推送镜像
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
        
    # 7. 服务器部署
    - name: 服务器部署
    uses: appleboy/ssh-action@v1
    with:
      host: ${{ secrets.SERVER_IP }}
      username: ${{ secrets.SERVER_USER }}
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      port: 22  # 明确指定端口
      script_timeout: 5m  # 增加超时时间
      script: |
        echo "连接成功！"
        docker login -u 本届最靓的仔 crpi-awpzezftnb095rf0.cn-hangzhou.personal.cr.aliyuncs.com
        docker pull ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
        docker stop mnist-container || true
        docker rm mnist-container || true
        docker run -d \
          --name mnist-container \
          -p 5000:5000 \
          -p 8000:8000 \
          ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: SSH连接测试
      uses: appleboy/ssh-action@v1
      with:
      host: ${{ secrets.SERVER_IP }}
      username: ${{ secrets.SERVER_USER }}
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      script: |
        echo "SSH连接成功！"
        whoami
        pwd
